//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use runtime::*;
use winapi::*;

use crate::externs::*;

fn init_memory(ctx: &mut Context, mappings: &mut kernel32::Mappings) {
    mappings.reserve(winapi::kernel32::Mapping {
        desc: "com".to_string(),
        addr: 0x100,
        size: 0xfc2,
        section: true,
    });
    let bytes = include_bytes!("../data/00000100.raw").as_slice();
    let out = &mut ctx.memory.bytes[0x100..][..bytes.len()];
    out.copy_from_slice(bytes);
}

pub fn x100(ctx: &mut Context) -> Cont {
    // 00000100 mov si,0F48h
    ctx.cpu.regs.set_si(0xf48u16);
    // 00000103 call 0106h
    ctx.call(0x106, Cont(x106))
}

pub fn x106(ctx: &mut Context) -> Cont {
    // 00000106 pop bp
    let x = ctx.pop16();
    ctx.cpu.regs.set_bp(x);
    // 00000107 add bp,0FFFAh
    ctx.cpu
        .regs
        .set_bp(add(ctx.cpu.regs.get_bp(), 0xfffau16, &mut ctx.cpu.flags));
    // 0000010a push bp
    let x = ctx.cpu.regs.get_bp();
    ctx.push16(x);
    // 0000010b push ax
    let x = ctx.cpu.regs.get_ax();
    ctx.push16(x);
    // 0000010c push bx
    let x = ctx.cpu.regs.get_bx();
    ctx.push16(x);
    // 0000010d push cx
    let x = ctx.cpu.regs.get_cx();
    ctx.push16(x);
    // 0000010e push dx
    let x = ctx.cpu.regs.get_dx();
    ctx.push16(x);
    // 0000010f push cs
    let x = ctx.cpu.regs.get_cs();
    ctx.push16(x);
    // 00000110 pop es
    let x = ctx.pop16();
    ctx.cpu.regs.set_es(x);
    // 00000111 push cs
    let x = ctx.cpu.regs.get_cs();
    ctx.push16(x);
    // 00000112 pop ds
    let x = ctx.pop16();
    ctx.cpu.regs.set_ds(x);
    // 00000113 mov cx,si
    ctx.cpu.regs.set_cx(ctx.cpu.regs.get_si());
    // 00000115 lea si,[bp+si+42h]
    ctx.cpu.regs.set_si(
        ctx.cpu
            .regs
            .get_bp()
            .wrapping_add(ctx.cpu.regs.get_si())
            .wrapping_add(0x42) as u16,
    );
    // 00000118 mov di,0FF82h
    ctx.cpu.regs.set_di(0xff82u16);
    // 0000011b shr cx,1
    ctx.cpu
        .regs
        .set_cx(shr(ctx.cpu.regs.get_cx(), 0x1u8, &mut ctx.cpu.flags));
    // 0000011d std
    std(ctx);
    // 0000011e push di
    let x = ctx.cpu.regs.get_di();
    ctx.push16(x);
    // 0000011f rep movsw
    ctx.rep(Rep::REP, Context::movsw);
    // 00000121 lea si,[di+2]
    ctx.cpu
        .regs
        .set_si(ctx.cpu.regs.get_di().wrapping_add(0x2) as u16);
    // 00000124 cld
    cld(ctx);
    // 00000125 stc
    stc(ctx);
    // 00000126 mov di,bp
    ctx.cpu.regs.set_di(ctx.cpu.regs.get_bp());
    // 00000128 ret
    ctx.ret(0)
}

const BLOCKS: [(u32, ContFn); 4] = [
    (0x100, x100),
    (0x106, x106),
    (0xff82, xff82),
    (runtime::RETURN_FROM_X86_ADDR, Context::return_from_x86),
];

pub const EXEDATA: EXEData = EXEData {
    bitness: 16,
    image_base: 0x100,
    resources: 0x0..0x0,
    blocks: &BLOCKS,
    init_memory,
    entry_point: Cont(x100),
};
