//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use runtime::*;
use winapi::*;

fn init_memory(ctx: &mut Context, mappings: &mut kernel32::Mappings) {
    mappings.reserve(winapi::kernel32::Mapping {
        desc: "com".to_string(),
        addr: 0x100,
        size: 0xff00,
        section: true,
    });
    let bytes = include_bytes!("../data/00000100.raw").as_slice();
    let out = &mut ctx.memory.bytes[0x100..][..bytes.len()];
    out.copy_from_slice(bytes);
}

pub fn x100(ctx: &mut Context) -> Cont {
    // 00000100 mov sp,8730h
    ctx.cpu.regs.set_sp(0x8730u16);
    // 00000103 cld
    cld(ctx);
    // 00000104 push ds
    ctx.push16(ctx.cpu.regs.get_ds());
    // 00000105 pop es
    let x = ctx.pop16();
    ctx.cpu.regs.set_es(x);
    // 00000106 mov cx,727Ch
    ctx.cpu.regs.set_cx(0x727cu16);
    // 00000109 mov di,14B4h
    ctx.cpu.regs.set_di(0x14b4u16);
    // 0000010c sub al,al
    ctx.cpu.regs.set_al(sub(
        ctx.cpu.regs.get_al(),
        ctx.cpu.regs.get_al(),
        &mut ctx.cpu.flags,
    ));
    // 0000010e rep stosb
    ctx.rep(Rep::REP, Context::stosb);
    // 00000110 mov ax,3508h
    ctx.cpu.regs.set_ax(0x3508u16);
    // 00000113 int 21h
    todo!();
}

const BLOCKS: [(u32, ContFn); 2] = [
    (0x100, x100),
    (runtime::RETURN_FROM_X86_ADDR, Context::return_from_x86),
];

pub const EXEDATA: EXEData = EXEData {
    bitness: 16,
    image_base: 0x100,
    resources: 0x0..0x0,
    blocks: &BLOCKS,
    init_memory,
    entry_point: Cont(x100),
};
