//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use runtime::*;

fn init_memory(ctx: &mut Context, mappings: &mut runtime::Mappings) {
    mappings.reserve(runtime::Mapping {
        desc: "com".to_string(),
        addr: 0x8230,
        size: 0x36,
        section: true,
    });
    let bytes = include_bytes!("../data/00008230.raw").as_slice();
    let out = &mut ctx.memory.bytes[0x8230..][..bytes.len()];
    out.copy_from_slice(bytes);
}

pub fn x100(ctx: &mut Context) -> Cont {
    // 00000100 mov al,13h
    ctx.cpu.regs.set_al(0x13u8);
    // 00000102 int 10h
    dos::int10(ctx);
    // 00000104 mov ax,0A000h
    ctx.cpu.regs.set_ax(0xa000u16);
    // 00000107 mov es,ax
    ctx.cpu.regs.set_es(ctx.cpu.regs.get_ax());
    Cont(x109)
}

pub fn x109(ctx: &mut Context) -> Cont {
    // 00000109 mov bp,0Ch
    ctx.cpu.regs.set_bp(0xcu16);
    Cont(x10c)
}

pub fn x10c(ctx: &mut Context) -> Cont {
    // 0000010c inc bp
    ctx.cpu
        .regs
        .set_bp(inc(ctx.cpu.regs.get_bp(), &mut ctx.cpu.flags));
    // 0000010d mov ax,0A00h
    ctx.cpu.regs.set_ax(0xa00u16);
    // 00000110 cwd
    ctx.cpu
        .regs
        .set_dx_ax(ctx.cpu.regs.get_ax() as i16 as i32 as u32);
    // 00000111 div bp
    let (quot, rem) = div(ctx.cpu.regs.get_dx_ax(), ctx.cpu.regs.get_bp() as u32);
    ctx.cpu.regs.set_ax(quot as u16);
    ctx.cpu.regs.set_dx(rem as u16);
    // 00000113 add ax,bx
    ctx.cpu.regs.set_ax(add(
        ctx.cpu.regs.get_ax(),
        ctx.cpu.regs.get_bx(),
        &mut ctx.cpu.flags,
    ));
    // 00000115 xchg si,ax
    let t = ctx.cpu.regs.get_si();
    ctx.cpu.regs.set_si(ctx.cpu.regs.get_ax());
    ctx.cpu.regs.set_ax(t);
    // 00000116 mov cx,140h
    ctx.cpu.regs.set_cx(0x140u16);
    Cont(x119)
}

pub fn x119(ctx: &mut Context) -> Cont {
    // 00000119 mov ax,10h
    ctx.cpu.regs.set_ax(0x10u16);
    // 0000011c mul cx
    let res = mul(
        ctx.cpu.regs.eax as u16 as u32,
        ctx.cpu.regs.get_cx() as u32,
        &mut ctx.cpu.flags,
    );
    ctx.cpu.regs.set_dx_ax(res);
    // 0000011e cwd
    ctx.cpu
        .regs
        .set_dx_ax(ctx.cpu.regs.get_ax() as i16 as i32 as u32);
    // 0000011f div bp
    let (quot, rem) = div(ctx.cpu.regs.get_dx_ax(), ctx.cpu.regs.get_bp() as u32);
    ctx.cpu.regs.set_ax(quot as u16);
    ctx.cpu.regs.set_dx(rem as u16);
    // 00000121 xor ax,si
    ctx.cpu.regs.set_ax(xor(
        ctx.cpu.regs.get_ax(),
        ctx.cpu.regs.get_si(),
        &mut ctx.cpu.flags,
    ));
    // 00000123 add al,bh
    ctx.cpu.regs.set_al(add(
        ctx.cpu.regs.get_al(),
        ctx.cpu.regs.get_bh(),
        &mut ctx.cpu.flags,
    ));
    // 00000125 and al,1Fh
    ctx.cpu
        .regs
        .set_al(and(ctx.cpu.regs.get_al(), 0x1fu8, &mut ctx.cpu.flags));
    // 00000127 stosb
    ctx.stosb();
    // 00000128 test di,di
    and(
        ctx.cpu.regs.get_di(),
        ctx.cpu.regs.get_di(),
        &mut ctx.cpu.flags,
    );
    // 0000012a loopne 0119h
    // Loopne not implemented
    todo!();
}

pub fn x12c(ctx: &mut Context) -> Cont {
    // 0000012c jne short 010Ch
    ctx.jne(Cont(x12e), Cont(x10c))
}

pub fn x12e(ctx: &mut Context) -> Cont {
    // 0000012e inc bx
    ctx.cpu
        .regs
        .set_bx(inc(ctx.cpu.regs.get_bx(), &mut ctx.cpu.flags));
    // 0000012f mov ah,1
    ctx.cpu.regs.set_ah(0x1u8);
    // 00000131 int 16h
    dos::int16(ctx);
    // 00000133 je short 0109h
    ctx.je(Cont(x135), Cont(x109))
}

pub fn x135(ctx: &mut Context) -> Cont {
    // 00000135 ret
    ctx.ret16(0)
}

const BLOCKS: [(u32, ContFn); 8] = [
    (0x8230, x100),
    (0x8239, x109),
    (0x823c, x10c),
    (0x8249, x119),
    (0x825c, x12c),
    (0x825e, x12e),
    (0x8265, x135),
    (runtime::RETURN_FROM_X86_ADDR, Context::return_from_x86),
];

pub const EXEDATA: EXEData = EXEData {
    bitness: 16,
    image_base: 0x100,
    resources: 0x0..0x0,
    blocks: &BLOCKS,
    init_memory,
    entry_point: Cont(x100),
};
